FirstShop/FirstShop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import TemplateView


urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html'), name='home'),
    path('jet/', include('jet.urls', 'jet')),
    path('admin/', admin.site.urls),
    path('carts/', include('apps.carts.urls')),
    path('orders/', include('apps.orders.urls')),
    path('catalog/', include('apps.catalog.urls')),
    path('shipments/', include('apps.shipments.urls')),
    path('payments/', include('apps.payments.urls')),
    path('products/', include('apps.products.urls')),
    path('delivery_api/', include('apps.delivery_api.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

FirstShop/apps/shipments/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'shipments'

urlpatterns = [
    path('', views.ShipmentList.as_view(), name='shipment_list'),
    path('<str:pub_id>/', views.ShipmentDetails.as_view(), name='shipment_details'),
]

FirstShop/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<title>
		{% block title %}
			Shipment
		{% endblock %}

	</title>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light" style="background-color: #e3f2fd;">
  <a class="navbar-brand" href="{% url 'shipments:shipment_list' %}">Shipment</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
         <a class="nav-link" href="{% url 'shipments:shipment_list' %}">List</a>
      </li>
      <li class="nav-item">
         <a class="nav-link" href="">Details</a>
      </li>
    </ul>
  </div>
</nav>

<div class="container mt-5">
  <div class="row">
    <div class="col-6 offset-md-2">
      {% block content %}

      {% endblock%}
    </div>
  </div>
</div>
    
</div>


</body>
</html>